baseurl = "https://richinsql.com"
DefaultContentLanguage = "en"
title = "Rich In SQL"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#googleAnalytics = "XXX"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[Params]
  homeTitle = "Rich In SQL"
  subtitle = "Just an Informatics Developer, finding their way..."
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = false
  hideAuthor = true
  gcse = "012345678901234567890:5fcdf1dc833dcb42a" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Rich"
  website = "richinsql.com"
  email = "hello@richinsql.com"
  
  github = "RichInSQL"
  #twitter = "RichInSQL"
  stackoverflow = "users/7096709/bonzaowl"
  youtube = "channel/UCktEGNKQ7NPgJLoVX_D7usg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/"
    weight = 2

[[menu.main]]
    parent = "About"
    name = "About Me"
    url = "/about"
    weight = 2

[[menu.main]]
    parent = "About"
    name = "Gear"
    url = "/gear"
    weight = 2

[[menu.main]]
    name = "References"
    url = "/"
    weight = 3

[[menu.main]]
  parent = "References"
  name = "Dates"
  url = "/dont-date-me"
  weight = 1

  [[menu.main]]
  parent = "References"
  name = "Books"
  url = "/library"
  weight = 2
