baseurl = "https://richinsql.com"
DefaultContentLanguage = "en"
title = "Rich In SQL"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#googleAnalytics = "XXX"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[Params]
  homeTitle = "Rich In SQL"
  subtitle = "Just an Informatics Developer, finding their way..."
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true

[Author]
  name = "Rich"
  website = "richinsql.com"
  email = "hello@richinsql.com"
  
  github = "RichInSQL"
  twitter = "RichInSQL"
  stackoverflow = "users/7096709/bonzaowl"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3